spring:
  ai:
    zhipuai:
      # api-key 使用你自己申请的进行替换；如果为了安全考虑，可以通过启动参数进行设置
      api-key: ${zhipuai-api-key}
      chat: # 聊天模型
        options:
          model: GLM-4V-Flash # GLM-4.1V-Thinking-Flash  # 视觉理解模型, 这个模型的上下文窗口 64K，比 GLM-4V-Flash 的 4K 可以返回更多的内容
          temperature: 0.1 # 低温度，保证提取的稳定性
  thymeleaf:
    cache: false

# 修改日志级别
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug